version: '2'
services:
  db:
    image: mysql:latest
    container_name: farmos-db
    network_mode: bridge
    volumes:
      - './.data/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: farmos
      MYSQL_DATABASE: farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: farmos

  www:
    depends_on:
      - db
    image: farmos/farmos:7.x-1.x
    container_name: farmos
    network_mode: bridge
    volumes:
      - './.data/www:/var/www/html'
    links:
      - db
    ports:
      - '80:80'
    environment:
      MYSQL_HOST: db:3306
      MYSQL_ROOT_PASSWORD: farmos
      MYSQL_DATABASE: farmos
      MYSQL_USER: farmos
      MYSQL_PASSWORD: farmos
      FARMOS_DEV: 'true'

