version: '2'
services:
  db:
    image: jsurf/rpi-mariadb
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm

  www:
    depends_on:
      - db
    image: frakman1/farmos-dev-pi:latest
    volumes:
      - './www:/var/www/html'
    ports:
      - '80:80'
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
